apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: DanielCok17/ambulance-ufe
  newName: DanielCok17/ambulance-ufe
  newTag: "v1.0.0"

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: xcok-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  xcok-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
