apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-updater
  namespace: wac-hospital
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: https://github.com/DanielCok17/xcok-gitops.git
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcd_bot
      messageTemplate: |
         Automated image update

         Automation name: {{ .AutomationObject }}

         Files:
         {{ range $filename, $_ := .Updated.Files -}}
         - {{ $filename }}
         {{ end -}}

         Images:
         {{ range .Updated.Images -}}
         - {{.}}
         {{ end -}}
    push:
      branch: main
  update:
    path: ./components/version-developers  # cesta kde chceme automaticky upraviť našu konfiguráciu
    strategy: Setters